### ISSUE TITLE
Script fails to bootstrap with Node v6.9.2

### ISSUE THREAD

**Issue by rahulthewall** [auth0-community/auth0-react-scripts#4]
### Description

Bootstrapping the example project with `create-react-app my-app --scripts-version auth0-react-scripts`

### Expected behavior

Create the example project

### Actual behavior

```
Error: Cannot find module '/Users/rahul/work/deep_impact/auth0_example/node_modules/react-scripts/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at checkNodeVersion (/usr/local/lib/node_modules/create-react-app/index.js:152:21)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/create-react-app/index.js:119:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Environment

1. Node v6.9.2
2. npm v3.10.8
3. Operating system: OS X 10.12.2

**Comment by unicodeveloper** [comment]
@rahulthewall Do you have yarn installed? If so, please uninstall it and let npm do the install.

There is currently a bug with yarn that says certain `package.json` files are missing

**Comment by rahulthewall** [comment]
@unicodeveloper No, I don't have yarn installed.

**Comment by unicodeveloper** [comment]
It works perfectly with npm. I can't reproduce the error with Npm. Please can you try again?

**Comment by dcanning** [comment]
output with yarn installed:

> C:\Repos> create-react-app my-app1 --scripts-version auth0-react-scripts
> Creating a new React app in C:\Repos\my-app1.
> 
> Installing packages. This might take a couple minutes.
> Installing react, react-dom, and auth0-react-scripts...
> 
> yarn add v0.21.3
> info No lockfile found.
> [1/4] Resolving packages...
> warning auth0-react-scripts > babel-preset-react-app > babel-preset-latest@6.14.0: �  preset-latest accomplishes the same task as babel-preset-env. �  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env �. And let us know how you're liking Babel at @babeljs on �
> [2/4] Fetching packages...
> warning fsevents@1.0.14: The platform "win32" is incompatible with this module.
> info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> warning "babel-loader@6.2.5" has unmet peer dependency "babel-core@^6.0.0".
> warning "babel-loader@6.2.5" has unmet peer dependency "webpack@1 || ^2.1.0-beta".
> warning "eslint-config-react-app@0.2.1" has unmet peer dependency "babel-eslint@6.1.2".
> warning "eslint-config-react-app@0.2.1" has unmet peer dependency "eslint@3.5.0".
> warning "eslint-config-react-app@0.2.1" has unmet peer dependency "eslint-plugin-flowtype@2.18.1".
> warning "eslint-config-react-app@0.2.1" has unmet peer dependency "eslint-plugin-import@1.12.0".
> warning "eslint-config-react-app@0.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@2.2.2".
> warning "eslint-config-react-app@0.2.1" has unmet peer dependency "eslint-plugin-react@6.3.0".
> warning "eslint-loader@1.5.0" has unmet peer dependency "eslint@>=1.6.0 <4.0.0".
> warning "eslint-plugin-flowtype@2.18.1" has unmet peer dependency "eslint@>=2.0.0".
> warning "eslint-plugin-import@1.12.0" has unmet peer dependency "eslint@2.x - 3.x".
> warning "eslint-plugin-jsx-a11y@2.2.2" has unmet peer dependency "eslint@^2.10.2 || 3.x".
> warning "eslint-plugin-react@6.3.0" has unmet peer dependency "eslint@^2.0.0 || ^3.0.0".
> warning "extract-text-webpack-plugin@1.0.1" has unmet peer dependency "webpack@^1.9.11".
> warning "html-webpack-plugin@2.22.0" has unmet peer dependency "webpack@*".
> warning "react-dev-utils@0.2.1" has unmet peer dependency "webpack@^1.13.2".
> warning "url-loader@0.5.7" has unmet peer dependency "file-loader@*".
> warning "webpack-dev-server@1.16.1" has unmet peer dependency "webpack@>=1.3.0 <3".
> warning "webpack-dev-middleware@1.10.2" has unmet peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
> warning "react-dom@15.5.4" has unmet peer dependency "react@^15.5.4".
> error Couldn't find a package.json file in "C:\\Repos\\my-app1\\node_modules\\auth0-react-scripts\\node_modules\\babel-preset-react-app"
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> 
> Aborting installation.
>   yarnpkg add --exact react react-dom auth0-react-scripts has failed.
> 
> Deleting generated file... node_modules
> Deleting generated file... package.json
> Deleting my-app1/ from C:\Repos
> Done.
> C:\Repos> node --version
> v6.9.2
> C:\Repos> npm --version
> 4.5.0
> C:\Repos> yarn --version
> 0.21.3

**after uninstalling yarn, the script worked fine.
npm uninstall -g yarn**

**Comment by andelar** [comment]
yarn is recommended with create-react-app 
Need to fix...
